#!/bin/sh 

#export TOOLCHAIN_DIR=$STAGING_DIR/toolchain-mipsel_24kc_gcc-7.5.0_musl
#mipsel-openwrt-linux-gcc -o helloworld helloworld.c

#export TOOLCHAIN_DIR=$STAGING_DIR/toolchain-arm_cortex-a9+vfpv3-d16_gcc-7.5.0_musl_eabi
#arm-openwrt-linux-gcc -o helloworld helloworld.c

#export TOOLCHAIN_DIR=$STAGING_DIR/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl
#aarch64-openwrt-linux-gcc -o helloworld helloworld.c

export STAGING_DIR=./staging_dir
export TOOLCHAIN_DIR=$STAGING_DIR/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl
export LDCFLAGS=$TOOLCHAIN_DIR/usr/lib
export LD_LIBRARY_PATH=$TOOLCHAIN_DIR/usr/lib
export PATH=$TOOLCHAIN_DIR/bin:$PATH


aarch64-openwrt-linux-gcc -o helloworld helloworld.c