#!/bin/sh

# automatic build maker

#build version
#
# Date of the build
#

DATE="2020-01-12"

NAME="GoldenOrb_"
CODE=$NAME$DATE
rm -rf ./files
mkdir -p ./files/etc

echo 'CODENAME="'"$CODE"'"' > ./files/etc/codename

echo "                            <model>" > ./files/etc/header_msg
echo "/img/header.png" >> ./files/etc/header_msg
echo "/img/rosy.jpg" >> ./files/etc/header_msg

BASE="openwrt-"
BASEO="openwrt-ar71xx-generic-tl-"
BASEQ="openwrt-ar71xx-generic-"
ENDO="-squashfs-factory"
ENDU="-squashfs-sysupgrade"

TYP="-GO"
END=$TYP$DATE

#
# change name of configuration file to match the desired router
#

cp ./configfiles/.config_name ./.config

DNS=$(cat "./.config" | grep "CONFIG_PACKAGE_dnsmasq-full=y")
if [ ! -z $DNS ]; then
	sed -i -e 's/CONFIG_PACKAGE_dnsmasq=y/# CONFIG_PACKAGE_dnsmasq is not set/g' ./.config
fi
WPAD=$(cat "./.config" | grep "CONFIG_PACKAGE_wpad-basic=y")
if [ ! -z $WPAD ]; then
	sed -i -e 's/CONFIG_PACKAGE_wpad-basic=y/# CONFIG_PACKAGE_wpad-basic is not set/g' ./.config
fi
WPAD=$(cat "./.config" | grep "CONFIG_PACKAGE_wpad=y")
if [ ! -z $WPAD ]; then
	sed -i -e 's/CONFIG_PACKAGE_wpad-mini=y/# CONFIG_PACKAGE_wpad-mini is not set/g' ./.config
fi

make V=s

#
# this part of the script does the copying, renaming and zipping of the image file(s)
#
# copy the section from imagecopy for your router
#

