#!/bin/sh /etc/rc.common

. /lib/functions.sh

START=99

log() {
	logger -t "Wifi MAC " "$@"
}

start()
{
	if [ ! -e /etc/wifimac ]; then
		echo "0" > /etc/wifimac
		log "Rename Wifi SSID"
		/usr/lib/custom/wifimac.sh &
	fi
}
